services:
  - type: web
    name: ZeliraSalesAI
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: GOOGLE_CLIENT_ID
        fromRender: true
      - key: GOOGLE_CLIENT_SECRET
        fromRender: true
      - key: OPENAI_API_KEY
        fromRender: true

